-- IMPORT ALL 595 COMPETITORS TO SUPABASE
-- Run this in Supabase SQL Editor

ALTER TABLE competitors DISABLE ROW LEVEL SECURITY;
ALTER TABLE competitor_locations DISABLE ROW LEVEL SECURITY;

INSERT INTO competitors (competitor_name, metal, use_category, region, business_type, price_positioning, national_chain, website, instagram_handle, facebook_account)
VALUES
('Akshaara Beautyhub', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gurudatha Gold Marchent', 'Gold', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jayanthi Diamonds & Jewellers Pvt Ltd', 'Multi-Metal', 'General', 'Andhra Style', 'Manufacturer', 'unknown', true, NULL, NULL, NULL),
('Lakshmi Tirumala Jewellery', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('SRI LAKSHMI NARASIMHA GOLD WORKS', 'Gold', 'Temple', 'Tamil Style', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Sree Sai Rajendra Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Girija Shankar Selections', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Varalaxmi Jewellery & Gold', 'Gold', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Venkateswara Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('ARNIKA SILVER JEWELLERY', 'Silver', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Bombay Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Kiranmayi Jewellery Mart', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mahendra Jewellery House', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rajendra Jewellers Wholesale Gold Shoppe', 'Gold', 'General', 'Andhra Style', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Sri Sanghvi Jewellers INDIA Pvt Ltd', 'Multi-Metal', 'General', 'Andhra Style', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Sridevi Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vega Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Vishal Silver', 'Silver', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kila Silver Jewellery', 'Silver', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('S J Gold Refinery', 'Gold', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Satyasri 1 Gram Jewellery & Fancy', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Kameswari Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Shakti Dharmakata', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Srinivasa Chaitanya Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Srinivasa Gold Refinery', 'Gold', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Swarna Jewellers', 'Gold', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vysyaraju Raju Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Yamini Silver Ware', 'Silver', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Arunachal Ivory And Ornaments', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Asb Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Asmi Diamonds', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Itanagar Jewels', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Melorra Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'unknown', false, NULL, NULL, NULL),
('R.J Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rani Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Reliance jewels', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'unknown', false, NULL, NULL, NULL),
('Shree Siyaram Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Star Gems House', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Balaji Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Blue Stone', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Caratlane', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'unknown', true, NULL, NULL, NULL),
('D N Jewellers', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gold Place Pvt Ltd', 'Gold', 'General', 'Assamese', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Jyoti Jewellers', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Prakash Jewellers', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Rajasthan Gems & Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Royal Gems & Jewellers', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tanishq', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'premium', true, NULL, NULL, NULL),
('ARCHNEH JEWELLERS', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Geetanjali Jewellery', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Maa Anjali Jewellers', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('N B Gems & Jewellers', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Nath Jewellery', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rattnanjalee Jewel India Pvt. Ltd.', 'Multi-Metal', 'General', 'Assamese', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Rupashree Assamese Traditional Jewellery', 'Multi-Metal', 'Traditional', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Samrat Jewellers', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shippan Gold Smith Jewellery', 'Gold', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Zangfai', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Bhargavi Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gopal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jainam Ornament Pvt. Ltd.', 'Multi-Metal', 'General', 'Pan-India', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Jewar Mahal', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kalyan Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'mid-premium', false, NULL, NULL, NULL),
('Khazaana Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kisna Diamond & Gold Jewellery', 'Gold+Diamond', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('PC Jeweller Ltd.', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Tanishq', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'premium', true, NULL, NULL, NULL),
('Tibetan Handicraft', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Alankar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Bhushan Bhandar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('JJ Gold', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jyoti Alankar', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kasturi Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('RADHE KRISHNA JEWELLERS', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ratnapriya Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sevika Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Kanak Dhara Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Anjalii Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Clt Annmol Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Navratan Gems & Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rakesh Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('SATI SHREE Jewellers & GEMS', 'Multi-Metal', 'Temple', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shah Jawaharlal Jethalal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sherlin Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Khatu Shyam Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Leela Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shubhkamana Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Anopchand Tilokchand Jewellers Flagship Store', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Anopchand Tilokchand Jewellers Pvt Ltd', 'Multi-Metal', 'General', 'Pan-India', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('Anopchand Tilokchand Jewellers Pvt.Ltd.', 'Multi-Metal', 'General', 'Pan-India', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('J.J.Gems & Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jewellers Sonia Sons', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Navkar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Samriddhi Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shah Jethalal Jadavji Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Al Hamd Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Arihant Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Femina Gold Palace', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Heritage Jewels', 'Multi-Metal', 'Traditional', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Kalamandir Jewellers Limited', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Omkar Gold', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Param Gold', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tanishq Jewellery', 'Multi-Metal', 'General', 'Maharashtrian', 'Chain', 'unknown', true, NULL, NULL, NULL),
('Anil Silvers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Anmol Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Bhalchandra Govind Mirkar & Sons Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Heritage Jewels', 'Multi-Metal', 'Traditional', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Jai Ambika Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jyotirling Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kanchan Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Meghna Jewellers Pvt Ltd', 'Multi-Metal', 'General', 'Maharashtrian', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Vishal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Arihant Gold Palace', 'Gold', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gharena Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Himatlal T Patadia Gems & Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Kalamandir Jewellers Ltd', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('M C Zaveri', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sonamahal Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Swastik Imitation', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vinayak Gold Palace', 'Gold', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Aditya Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Dhanraj Jewels', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jupiter Lifestyle Pvt. Ltd.,Jupiter Lifestyle', 'Multi-Metal', 'General', 'Gujarati', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Oms Group', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Popular Jewels', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Sai Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Tulja Jewellers Dholrawala', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Amrut Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Soni Fashion', 'Multi-Metal', 'Contemporary', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vagheshvari Gold Art', 'Gold', 'Contemporary', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('A-One Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Amideep Jewels', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Arihant Gems and Jewellers Pvt Ltd', 'Multi-Metal', 'General', 'Gujarati', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Arihant Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Charu Jewels', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('D J Designer Jewellery', 'Multi-Metal', 'Contemporary', 'Gujarati', 'Boutique', 'unknown', false, NULL, NULL, NULL),
('Divera Diamond Jewellery', 'Diamond', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gangaur Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Haveli Gold', 'Gold', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Indriya (Arihant Mall)', 'Multi-Metal', 'General', 'Gujarati', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('KHUSHALBHAI Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kalamandir Jewellers Limited', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Muddra Gems and Jewelary', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Navinchandra Hirachand Malji Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Palaksh Jewelry', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('R S Sakhiya Diamond', 'Diamond', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rajwadi Gold Palace', 'Gold', 'General', 'Gujarati', 'Showroom', 'mid-premium', false, NULL, NULL, NULL),
('Rameshwar Swarna Mandir Pvt Ltd', 'Gold', 'General', 'Gujarati', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Royal Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shine Designs', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shiv Krishna Diamond', 'Diamond', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Swarna Kalash Jewellers', 'Gold', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Swastik Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('The Creative Box', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Umiya Gold Palace', 'Gold', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vishnu Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Zota Jewel', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Arbuda Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ashapuri Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Baroda Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kalamandir Jewellers Ltd', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Maa Ashapuri Silver House', 'Silver', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mevada Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('N K Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Nandlal Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Parovani Point', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Radhika Jewellers', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('B.L & Sons Jewellers', 'Multi-Metal', 'General', 'North Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Caratlane', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'unknown', true, NULL, NULL, NULL),
('Chand Gems And Jewellery Pvt. Ltd', 'Multi-Metal', 'General', 'Pan-India', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Durga Gold and Silver House', 'Gold+Silver', 'General', 'North Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Giva - Faridabad - Sector 15', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jauhreez - Agarwal Abhushan Bhandar', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('PC Jeweller Ltd.', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Prabhu Dayal & Sons Jewellers Pvt Ltd. (Since 1967)', 'Multi-Metal', 'General', 'North Indian', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Swastik Shree Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tanishq', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'premium', true, NULL, NULL, NULL),
('A D Jewellers', 'Multi-Metal', 'General', 'North Indian', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('Aashirwad Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Dhirsons Jewellery House', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jiyo Created Diamonds & Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Naresh Jewellers Pvt Ltd', 'Multi-Metal', 'General', 'North Indian', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('P P Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Prabhu Dayal Malhotra & Sons Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Giriraj Jewellers Since 2002', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Raghuveer Jeweller Pvt Ltd', 'Multi-Metal', 'General', 'North Indian', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Tanishq', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'premium', true, NULL, NULL, NULL),
('Aakash Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Caratlane', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'unknown', true, NULL, NULL, NULL),
('Fateh Chand Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('Kiner Kailash Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Lal Jee Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ratra Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tangri Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tanishq', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'premium', true, NULL, NULL, NULL),
('Verma Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Abhushan INDIA Pvt Ltd', 'Multi-Metal', 'General', 'Pan-India', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Kangan Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Laxmi Jewellery House', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('M R Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mukesh Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Narendra Keshavlal & Sons Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('New Sona Chandi Gold Cash', 'Gold+Silver', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('The Dacca Jewellery & Mina House', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Uma Jewellery Works', 'Multi-Metal', 'General', 'Pan-India', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Vinayak Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Abhushan Alankar Jewellers & Bartan', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gaytri Alankar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jevar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('K.V.R Fashion Jewellers', 'Multi-Metal', 'Contemporary', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pearl House', 'Pearl', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ranchi Silvers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Balajee Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sita Ram Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Shyam Alankar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tiru Bala Ji Jewellers Pvt Ltd', 'Multi-Metal', 'General', 'Pan-India', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Daulath Krishna Jewellers Silver Palace', 'Silver', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Makam Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mandoth Jewellers and Bankers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Milan Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mivaan Fine Jewels', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('New Mathaji Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Nk Designers & Jewellerys', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Padmapriya jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Prakash Jewellers', 'Multi-Metal', 'General', 'Assamese', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Sri Ganesh Diamonds & Jewellery', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Akshata Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Era Italian Silver', 'Silver', 'General', 'South Indian', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('G T C And Jewellery', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Haji Gold', 'Gold', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Iqra Gold', 'Gold', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('New Arun Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Prasanna Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('S L Shet Diamond House', 'Diamond', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sharmila Jewellery Bharath Finance', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Laxmi Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('A Shankara Chetty & Sons', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Chamundeshwari Gold & Silver', 'Gold+Silver', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Cvr Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Cvr Luxury Family Store', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Guru Diamonds And Jewellery Works', 'Multi-Metal', 'General', 'South Indian', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Lalitha Jewellery Mart', 'Multi-Metal', 'General', 'South Indian', 'Chain', 'unknown', false, NULL, NULL, NULL),
('New Shubhm Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('R R Jeweller', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sharada Jewellers', 'Multi-Metal', 'General', 'South Indian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Vimaleshwara Jewellery Works', 'Multi-Metal', 'General', 'South Indian', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Ishal Rental Jewellery', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Khaira - Rental Jewellery', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kollam Supreme', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Lulu Fashion Jewellery', 'Multi-Metal', 'Contemporary', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Nakshatra Gold and Diamonds', 'Gold', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Palace Jewellery', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rajadhani Jewellery', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Amaya The Jewel Boutique', 'Multi-Metal', 'Contemporary', 'Kerala Style', 'Boutique', 'unknown', false, NULL, NULL, NULL),
('Cammilli Diamond and Gold', 'Gold+Diamond', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Diya Gold And Diamonds', 'Gold', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('IMG GOLD BUYERS', 'Gold', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jewellery By La Broiche', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('MINAR FASHION JEWELLERY', 'Multi-Metal', 'Contemporary', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Nirmaliyam Jewellery', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sai Pearls & Gems', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shazana Gold and Diamond', 'Gold+Diamond', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Silver Shop', 'Silver', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Malavika Jewellers', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Manjali Thrissur Fashion Jewellers', 'Multi-Metal', 'Contemporary', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Oh By Ozy', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('PereppadanS Gold & Diamonds', 'Gold', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Phoenix Gold and Silver', 'Gold+Silver', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sree Ajaya Jewellery', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sree Subbiah Jewellers', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Subbiah Jewellery', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Theertham Jewellers', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Thrissur Grace Jewellery', 'Multi-Metal', 'General', 'Kerala Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Agarwal Diamond', 'Diamond', 'General', 'Pan-India', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('Amrapali Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Amrapali Jewellers Ratan Showroom', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Chandrapushp Johari Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('Johri Bandhu Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kisna Diamond & Gold Jewellery', 'Gold+Diamond', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Krishnam Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('New Shri Krishna Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Ganesh Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Swarna Sukh', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Agarwal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('Ganpat Lal Keshrimal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Manish Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Muskan Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ornam Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rama Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ratanlal Saraf Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Siddhivinayak Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Suvarna Jewels', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Wedding Point', 'Multi-Metal', 'Bridal', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Banarasi Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Jewellers Madanlal Chhaganlal', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jewellers Nanabhai', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Maanik Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('New Krishna Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rajat Gems & Jewelleries', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ratna House Jewel', 'Gemstone', 'General', 'Pan-India', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('Vishal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Yashika Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Abhushan Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Arihant Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Chandukaka Saraf Pvt Ltd', 'Multi-Metal', 'General', 'Maharashtrian', 'Manufacturer', 'unknown', true, NULL, NULL, NULL),
('Deepak Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Dev Bhairav Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Dinesh Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Heritage Jewels', 'Multi-Metal', 'Traditional', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Indriya (R City Mall)', 'Multi-Metal', 'General', 'Maharashtrian', 'Retail Store', 'unknown', true, NULL, NULL, NULL),
('J S J', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tanishq Jewellery', 'Multi-Metal', 'General', 'Maharashtrian', 'Chain', 'unknown', true, NULL, NULL, NULL),
('Bafna Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Bgr Walokar Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Chimurkar Brothers Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Karan Kothari Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Londe Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('M. Dhomne Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Parekh Brothers Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pramod Jewellers & Gift Centre', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rokde Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('SHREE JEWELLERS & SAREES', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('A S Ashtekar Saraf', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Aarya Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Arvind Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Deepak Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kulswamini Jewellers Jalgaonkar', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ms Narayan Gopalsheth Adgaonkar', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Nrutyaa Diamond Jewellery', 'Diamond', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pournima Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('VADNERE SARAF', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Yashwant Martand Maind', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gold Mart Jewellers', 'Gold', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Pawan Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('RMK Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ratnamani Gems and Jewellery', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Jagdamba Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Radhe Pearls', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tapadia Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('V K MALI JEWELLERS', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Carat Lane', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gomti Jewellery Cum Handloom House', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Hakim Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jash Kangabam', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Krishna Prasad Gemstone And Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Manikchand Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rm Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('S R Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Manikumar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tanishq', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'premium', true, NULL, NULL, NULL),
('Aarohana.Official (Crystal)', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Lafsana Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('M P J Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Manik Chand Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Santoshi Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sham Singh Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Soumya Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Star Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Swarnadeep Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Trreasure Hut', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Caratlane', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'unknown', true, NULL, NULL, NULL),
('M S Goldsmith', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Manisha Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mia By Tanishq', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'unknown', false, NULL, NULL, NULL),
('Nirmala Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Remna Gold & Jewellery (Rgj Goldsmith)', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Silver Paradise', 'Silver', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sparks', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('T B C Store Wholesale And Retail', 'Multi-Metal', 'General', 'Pan-India', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('Zopa Gold Smith', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Bonafide', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ishaan Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kk Sunari Shop', 'Multi-Metal', 'Daily Wear', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Life Style (Sonu)', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('MiachicO jewellery Shop', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Paul Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rj & Sons', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Suman Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tanishq', 'Multi-Metal', 'General', 'Pan-India', 'Chain', 'premium', true, NULL, NULL, NULL),
('YSR Pearls', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Anil Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Anil Silvers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Chandukaka Saraf Pvt Ltd', 'Multi-Metal', 'General', 'Maharashtrian', 'Manufacturer', 'unknown', true, NULL, NULL, NULL),
('Femina Gold Palace', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Heritage Jewels', 'Multi-Metal', 'Traditional', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Indriya (R City Mall)', 'Multi-Metal', 'General', 'Maharashtrian', 'Retail Store', 'unknown', true, NULL, NULL, NULL),
('Kalamandir Jewellers Limited', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Manisha Art Jewellers', 'Multi-Metal', 'Contemporary', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vishal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('916 Kashinath Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Agarwal Diamond Jewellers', 'Diamond', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Chandi Bhandar', 'Silver', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Hemji Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Hemraj Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kgn Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Khimji Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Collection', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Swarna Alankar Jewellers', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vinayaklal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Amar and Sons Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ashish jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Billa Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gurdeep Singh & Sons Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kimti Lal & Sons', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('M Kaur Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Retail Store', 'unknown', false, NULL, NULL, NULL),
('Piara Singh & Sons', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Raj Kumar & Sons Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Guru Ram Dass Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Sahib Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Bhatia & Company Nagan Wale', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Chaman Lal Subhash Chander Jewellers Legacy Pvt Ltd', 'Multi-Metal', 'General', 'Punjabi', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Devki Nandan Meharchand Sekhri Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gems INDIA', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kanda Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Palak Traders', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('RS Gold Byers - Sell Your Gold For Cash', 'Gold', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Satnam Gems & Jewellery', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Ganpati Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Varun Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Canady Jewellers (Rummi Wale)', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gupta Art Jewellery', 'Multi-Metal', 'Contemporary', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jain Silver Creations Or Momentz', 'Silver', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mona Traderss', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Panjaab Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pink City Handicraft', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Raghbir Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('V P Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('VIRK Jewellers', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('WAZIR JEWELLERS', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Balaji Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Daulatram Churuwala And Sons (DRS)', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('JKJ & Sons Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('JKJ Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jmj Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Khandelwal Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Orissa Jewels', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Psj Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Psj Jewellers Jaipur', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Hari Jwellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kawaakari Silver Jewellery', 'Silver', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ladli Imitation', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mahalaxmi Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pure Gold Jodhpur', 'Gold', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Radha Rani Artificial Jewellery', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shivaji Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Dwareka Dheesh Jewellerys', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Kana Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vardhaman Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Alankar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Ambesh Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Auric Jewels', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('K T School Uniform', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pristine Jewels', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('RR Gems & Jewels', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('RoopShree Art Jewellery', 'Multi-Metal', 'Contemporary', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rp Gold 1gm', 'Gold', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree R B Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sunder Jewellers', 'Multi-Metal', 'General', 'Rajasthani', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Chakravarti Verma Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pieces Of Me', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pristine', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ram Chandra Pradeep Kumar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ramchandra Rajkumar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Senco Gold & Diamonds', 'Gold', 'General', 'Pan-India', 'Chain', 'unknown', false, NULL, NULL, NULL),
('Shakya Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Ganapati Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Z & C Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Dev Silver & Gold', 'Gold+Silver', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Goutham Jewellers', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gowry Jewellery Mart', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jayaram Jewellers', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jhillmill Fashion Jewellery', 'Multi-Metal', 'Contemporary', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Konika Jewellery Pvt Ltd', 'Multi-Metal', 'General', 'Tamil Style', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Mahaveer Gold Palace', 'Gold', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Om Sri Viswakarama Gold Company', 'Gold', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Omr Bazaar Street', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Swarna Maligai Jewellery', 'Gold', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Akshaya Jewellery', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Dhruva Diamonds and Jewels', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jeeva Trenz', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kumaran Chain Shop', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sree Ranga Jewellers', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Mahalakshmi Jewellers', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Mangalam Jewellery', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Muhurtha Jewels', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vidhyass Designer Jewellers Boutique', 'Multi-Metal', 'Contemporary', 'Tamil Style', 'Boutique', 'unknown', false, NULL, NULL, NULL),
('Viyaan Jewellery', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Balan Jewellers', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Gkv Gold', 'Gold', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('SRI Puspha Nagaimaligai', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Seenu Jewellery', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Siva Thanga Meenakshi Jewellers', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sreenivasan Jewellery', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Balambigai Jewellery Mart', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Kamatchi Jewellers', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Muthu Jewellers', 'Pearl', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Thanga Meenakshi Jewellers', 'Multi-Metal', 'General', 'Tamil Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Jauhari Jewellers Crafted For You', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Krishna Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Ksb Gold Works', 'Gold', 'General', 'Andhra Style', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Lotus Silver Jewellery', 'Silver', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('R R Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Rajshree Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('The Diamond Store By Chandubhai', 'Diamond', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vega Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Aparana Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jayanthi Diamonds & Jewellers Pvt Ltd', 'Multi-Metal', 'General', 'Andhra Style', 'Manufacturer', 'unknown', true, NULL, NULL, NULL),
('Kothakonda Silver Palace Jewellers & Gems', 'Silver', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Padmavathi Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('SAI Maruthi Jewellers Show Room', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Siri Pearls & Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Soumya Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Sumangali Sarees And Ladies Emporium', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Venus Jewellers', 'Multi-Metal', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vuppula Shiva Chidanbaraiah Gold and Sliver Merchants', 'Gold', 'General', 'Andhra Style', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Chandrani Pearls', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kalika Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Moni Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('New Saha Jewellery & Sons', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Radha Krishna Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Radhakrishna Jewellery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sabitri Gold Plating Jewellery', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sananda Jewelery', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Krishna Gold Plating Jewellery', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Swarnakamal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Dau Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jewel Empire', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Laxmi Narain Sons', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('M.K. Creation', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pc Jeweller Limited', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sachin Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shiri Nath Ji Sarraf', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Suresh Chand Neeraj Kumar Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('The Rose Gold', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('V J Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kamakshi Jewellers & Ratna Kendra', 'Gemstone', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kamal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kashi Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kumar Jewellers & Rashi Ratna Kendra ( Bilhaur Wale)', 'Gemstone', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Laxmi Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mani Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Narayan Mangal Diamond Business', 'Diamond', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Jouhari Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('The Kaushal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('VAGMI R. A. JEWELLERS', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Anil Kumar Nitish Kumar Jain Jewellers Pvt. Ltd', 'Multi-Metal', 'General', 'Pan-India', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Archvin''s International', 'Multi-Metal', 'General', 'Pan-India', 'Exporter', 'unknown', false, NULL, NULL, NULL),
('Bansal Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Jewels Box (Gold & Diamond)', 'Gold+Diamond', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Khun Khun Ji Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kishori Ji Jewels', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Lucknow Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Punjab Jewellers and Sons', 'Multi-Metal', 'General', 'Punjabi', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shri Khun Khun Ji Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sri Badri Saraf - Singar Nagar Wale', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('1 One Gram Gold Jewellery (Khattri Creation)', 'Gold', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Chetmani Gems & Jewels Private Limited (Ravindrapuri)', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Chetmani Gems & Jewels Pvt Ltd (Flagship Store)', 'Multi-Metal', 'General', 'Pan-India', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Kanhaiya Lal Saraf Jewellers Trueso', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Makund Das Narsingh Das Sonawala', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pavitrani Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Preetam Jewellers Nxt', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Shree Banaras Jewels Pvt. Ltd.', 'Multi-Metal', 'General', 'Pan-India', 'Manufacturer', 'unknown', false, NULL, NULL, NULL),
('Shri Banaras Swarn Kala Kendra', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Vijay Alankar Mandir', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Anil Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Dev Bhairav Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Dinesh Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Heritage Jewels', 'Multi-Metal', 'Traditional', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Heritage Jewels', 'Multi-Metal', 'Traditional', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Indriya', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Indriya (R City Mall)', 'Multi-Metal', 'General', 'Maharashtrian', 'Retail Store', 'unknown', true, NULL, NULL, NULL),
('J S J', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Kalamandir Jewellers Limited', 'Multi-Metal', 'General', 'Gujarati', 'Showroom', 'unknown', true, NULL, NULL, NULL),
('Leelaz Jewel Paradise', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('MY BEAUTY SHOPSS', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mahalaxmi Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Meera Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Mukesh Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Pednekar Suvarna Palace', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sagarjewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sanghvi Dalichand Chimnaji Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Sha Dhanaji Poonamchand Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Tulsi Jewellers', 'Multi-Metal', 'General', 'Maharashtrian', 'Showroom', 'unknown', false, NULL, NULL, NULL),
('Virasat Jewellers', 'Multi-Metal', 'General', 'Pan-India', 'Showroom', 'unknown', false, NULL, NULL, NULL)
ON CONFLICT (competitor_name) DO NOTHING;

ALTER TABLE competitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitor_locations ENABLE ROW LEVEL SECURITY;
